name: Stock Manager
version: "0.3.9"
slug: stock_manager
description: Sistema de gestión de inventario doméstico con escáner de códigos de barras
url: https://github.com/Mixtax32/stock-manager-addon
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface
webui: http://[HOST]:[PORT:8099]
panel_icon: mdi:package-variant
panel_title: Stock Manager
ingress: true
ingress_port: 8099
panel_admin: false
startup: application
boot: auto
options:
  log_level: info
schema:
  log_level: list(debug|info|warning|error)
